include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    prefer_const_constructors: ignore ignore
    depend_on_referenced_packages: ignore
    non_constant_identifier_names: ignore
    prefer_const_literals_to_create_immutables: ignore
    unused_import: ignore
